fieldLayouts:
  31a0dabf-f6c4-41b1-be5e-e5a46f7f3b2a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 808a3bb6-a66d-4a28-8a4d-43d8e723677f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 639a69ad-d5f3-4057-8d87-137c69661c57 # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96d4d1b3-3cd7-4295-af21-2b0ee53d7599
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f2f10eba-1a45-41d9-9e63-c76bcb33a98b # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6f216e2-25f9-4ee2-a44b-3fceb050ff7e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 391edf64-1c2c-4f87-9435-12378d9e9f00
        userCondition: null
handle: album
hasTitleField: false
name: Album
section: 1fb2a281-789b-47cd-bd5c-d568da249a35 # Album
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
