fieldLayouts:
  e6827c04-474b-4ae4-9ad7-8221b276a05f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4a2dbfbc-7c6a-4b0e-9ec5-05516f531749
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: b4e053c8-1682-40bd-8a92-1e7d04d0b27b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6e80dd84-d816-44bf-9e04-3a94bf186d1b
        userCondition: null
fs: backgroundImage
handle: backgroundImage
name: 'Background Image'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
