columnSuffix: nkacqcru
contentColumnType: string
fieldGroup: 592d68f4-b1af-4517-93fc-ad9dadb2ab09 # About
handle: bannerImage
instructions: null
name: 'Banner Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:651cb76d-e620-419f-9030-4a6c45f86ed3' # Background Image
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:651cb76d-e620-419f-9030-4a6c45f86ed3' # Background Image
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
