columnSuffix: cpiocrfg
contentColumnType: boolean
fieldGroup: 592d68f4-b1af-4517-93fc-ad9dadb2ab09 # About
handle: isform
instructions: null
name: isForm
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
