dateModified: 1720781464
email:
  fromEmail: dev-test@yoo.digital
  fromName: 293-m-project
  transportType: craft\mail\transportadapters\Sendmail
fs:
  backgroundImage:
    hasUrls: true
    name: 'Background Image'
    settings:
      path: '@webroot/images/uploads/background'
    type: craft\fs\Local
    url: '@web/images/uploads/background'
  logo:
    hasUrls: true
    name: Logo
    settings:
      path: '@webroot/images/uploads/logo'
    type: craft\fs\Local
    url: '@web/images/uploads/logo'
meta:
  __names__:
    1c2c9305-05ec-4708-a9bc-b5bb20733aac: 'Banner Image' # Banner Image
    1fb2a281-789b-47cd-bd5c-d568da249a35: Album # Album
    39b1bd22-567b-4b8c-a35e-1812f761a414: Introduction # Introduction
    44b1b133-2a7f-410d-a791-d08d689ced20: homepage # homepage
    58e5330c-b0ef-43ce-bc09-04944358f3ee: 293-m-project # 293-m-project
    0223b707-3c9a-486e-8d9f-4e0a9b65b004: 293-m-project # 293-m-project
    592d68f4-b1af-4517-93fc-ad9dadb2ab09: About # About
    639a69ad-d5f3-4057-8d87-137c69661c57: Logo # Logo
    651cb76d-e620-419f-9030-4a6c45f86ed3: 'Background Image' # Background Image
    af759e79-21b3-42cc-8aa1-9b9ac64c6157: YouTube # YouTube
    ba830877-e04b-4616-808c-6b8461b0b2e2: About # About
    bbe39bbb-a257-4541-858e-f14fcde1a993: YouTube # YouTube
    d2f9ed8d-d015-40ee-91a5-8d893b010e25: 'Info Text' # Info Text
    d14d2f9e-1b65-4dc6-8871-dfabe0db522f: Default # Default
    d3297840-9fce-4338-9145-1a95555ad540: IsForm # IsForm
    e64fed43-43e3-4ef1-bd91-cba55dff1e11: homepage # homepage
    e95a0410-74a3-4886-aff5-f90c5936225c: Album # Album
    f2f10eba-1a45-41d9-9e63-c76bcb33a98b: 'Background Image' # Background Image
    f8041b4b-1238-4323-a5c5-ee22373ce456: Logo # Logo
    f3796036-0ba8-4173-b40f-873b81ef93c2: Common # Common
    faba4b5e-82a2-478b-bd0b-4750e64b6d78: IsLocation # IsLocation
plugins:
  architect:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  contact-form-honeypot:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  craft-components:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  project-extension:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
system:
  edition: solo
  live: true
  name: 293-m-project
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
